// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThinkTogether.Infrastructure.Persistence;

#nullable disable

namespace ThinkTogether.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122072906_AddQuestionManagement")]
    partial class AddQuestionManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idThachThuc");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiTao");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("moTa");

                    b.Property<int>("PlayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("luotChoi");

                    b.Property<Guid>("QuizSetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBoTracNghiem");

                    b.Property<string>("ShareLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("urlChiaSe");

                    b.Property<bool>("ShowLeaderboard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("hienThiBangXepHang");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThai");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieuDe");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("QuizSetId");

                    b.HasIndex("ShareLink")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Status", "DeletedAt", "PlayCount");

                    b.ToTable("ThachThuc", null, t =>
                        {
                            t.HasCheckConstraint("CK_ThachThuc_luotChoi", "luotChoi >= 0");

                            t.HasCheckConstraint("CK_ThachThuc_trangThai", "trangThai IN ('Active', 'Archived')");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Entities.ChallengeAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauTraLoi");

                    b.Property<Guid>("ChallengeAttemptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idLuotChoiThachThuc");

                    b.Property<Guid?>("ChallengeAttemptId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("dung");

                    b.Property<int>("PointsEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diemDat");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoi");

                    b.Property<int>("SubmissionTimeMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("thoiGianNopMs");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeAttemptId");

                    b.HasIndex("ChallengeAttemptId1");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ChallengeAttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("CauTraLoiThachThuc", null, t =>
                        {
                            t.HasCheckConstraint("CK_CauTraLoiThachThuc_diemDat", "diemDat >= 0");

                            t.HasCheckConstraint("CK_CauTraLoiThachThuc_thoiGianNopMs", "thoiGianNopMs >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Entities.ChallengeAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idLuotChoi");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idThachThuc");

                    b.Property<Guid?>("ChallengeId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianHoanTatLuot")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("CompletionTimeMs")
                        .HasColumnType("int")
                        .HasColumnName("thoiGianHoanThanhMs");

                    b.Property<int>("CorrectAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soCauDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bietDanh");

                    b.Property<int>("ScoreAchieved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diemDat");

                    b.Property<int>("TotalQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("tongSoCau");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("ChallengeId1");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Nickname");

                    b.HasIndex("UserId");

                    b.HasIndex("ChallengeId", "ScoreAchieved", "CompletedAt");

                    b.ToTable("LuotChoiThachThuc", null, t =>
                        {
                            t.HasCheckConstraint("CK_LuotChoiThachThuc_diemDat", "diemDat >= 0");

                            t.HasCheckConstraint("CK_LuotChoiThachThuc_soCauDung", "soCauDung >= 0 AND soCauDung <= tongSoCau");

                            t.HasCheckConstraint("CK_LuotChoiThachThuc_thoiGian", "thoiGianHoanThanhMs IS NULL OR thoiGianHoanThanhMs > 0");

                            t.HasCheckConstraint("CK_LuotChoiThachThuc_tongSoCau", "tongSoCau >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.ClassAggregate.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idLopHoc");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("urlAnhBia");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("moTa");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("maLop");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenLop");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idGiaoVien");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("LopHoc", null, t =>
                        {
                            t.HasCheckConstraint("CK_LopHoc_maLop", "LEN(maLop) = 8");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.ClassAggregate.Entities.ClassMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idThanhVien");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idLopHoc");

                    b.Property<Guid?>("ClassId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayThamGia")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayRoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassId1");

                    b.HasIndex("UserId");

                    b.HasIndex("ClassId", "UserId")
                        .IsUnique();

                    b.ToTable("ThanhVienLop", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.ClassAggregate.Entities.Homework", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBaiTapVeNha");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayGiao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idLopHoc");

                    b.Property<Guid?>("ClassId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hanChot");

                    b.Property<Guid>("QuizSetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBoTracNghiem");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieuDe");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassId1");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("DueDate");

                    b.HasIndex("QuizSetId");

                    b.HasIndex("ClassId", "DueDate");

                    b.ToTable("BaiTapVeNha", null, t =>
                        {
                            t.HasCheckConstraint("CK_BaiTapVeNha_hanChot", "hanChot IS NULL OR hanChot >= ngayGiao");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.ClassAggregate.Entities.HomeworkSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBaiNop");

                    b.Property<Guid>("ChallengeAttemptId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idLuotChoiThachThuc");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<Guid>("HomeworkId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBaiTapVeNha");

                    b.Property<Guid?>("HomeworkId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diem");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThai");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiDung");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianNop")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeAttemptId")
                        .IsUnique();

                    b.HasIndex("HomeworkId1");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.HasIndex("HomeworkId", "StudentId")
                        .IsUnique();

                    b.ToTable("BaiNop", null, t =>
                        {
                            t.HasCheckConstraint("CK_BaiNop_diem", "diem >= 0");

                            t.HasCheckConstraint("CK_BaiNop_trangThai", "trangThai IN ('Submitted', 'Late', 'NotSubmitted')");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.Entities.GamePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiChoi");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThaiKetNoi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPhienChoi");

                    b.Property<Guid?>("GameSessionId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bietDanh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("GameSessionId1");

                    b.HasIndex("GameSessionId", "CreatedAt");

                    b.ToTable("NguoiChoiPhien", null, t =>
                        {
                            t.HasCheckConstraint("CK_NguoiChoiPhien_bietDanh", "LEN(bietDanh) >= 2 AND LEN(bietDanh) <= 100");

                            t.HasCheckConstraint("CK_NguoiChoiPhien_trangThaiKetNoi", "trangThaiKetNoi IN ('Connected', 'Disconnected')");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.Entities.GameQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoiPhien");

                    b.Property<decimal>("AverageResponseTimeMs")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("thoiGianTraLoiTrungBinh");

                    b.Property<int>("CorrectAnswerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soTraLoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPhienChoi");

                    b.Property<Guid?>("GameSessionId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PositionInGame")
                        .HasColumnType("int")
                        .HasColumnName("viTriTrongPhien");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.Property<int>("WrongAnswerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soTraLoiSai");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("GameSessionId1");

                    b.HasIndex("QuestionId");

                    b.HasIndex("GameSessionId", "PositionInGame")
                        .IsUnique();

                    b.ToTable("CauHoiPhienChoi", null, t =>
                        {
                            t.HasCheckConstraint("CK_CauHoiPhienChoi_soTraLoiDung", "soTraLoiDung >= 0");

                            t.HasCheckConstraint("CK_CauHoiPhienChoi_soTraLoiSai", "soTraLoiSai >= 0");

                            t.HasCheckConstraint("CK_CauHoiPhienChoi_thoiGian", "thoiGianTraLoiTrungBinh >= 0");

                            t.HasCheckConstraint("CK_CauHoiPhienChoi_viTriTrongPhien", "viTriTrongPhien >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.Entities.GameScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idDiem");

                    b.Property<decimal>("AccuracyPercentage")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tiLeChinhXac");

                    b.Property<int>("CorrectAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soCauDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<int?>("FinalRank")
                        .HasColumnType("int")
                        .HasColumnName("xepHangCuoi");

                    b.Property<Guid>("GamePlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiChoi");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPhienChoi");

                    b.Property<Guid?>("GameSessionId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("tongDiem");

                    b.Property<int>("TotalQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("tongSoCau");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("GamePlayerId")
                        .IsUnique();

                    b.HasIndex("GameSessionId");

                    b.HasIndex("GameSessionId1");

                    b.HasIndex("GameSessionId", "FinalRank");

                    b.HasIndex("GameSessionId", "TotalPoints");

                    b.ToTable("DiemPhienChoi", null, t =>
                        {
                            t.HasCheckConstraint("CK_DiemPhienChoi_soCauDung", "soCauDung >= 0 AND soCauDung <= tongSoCau");

                            t.HasCheckConstraint("CK_DiemPhienChoi_tiLeChinhXac", "tiLeChinhXac >= 0 AND tiLeChinhXac <= 100");

                            t.HasCheckConstraint("CK_DiemPhienChoi_tongDiem", "tongDiem >= 0");

                            t.HasCheckConstraint("CK_DiemPhienChoi_tongSoCau", "tongSoCau >= 0");

                            t.HasCheckConstraint("CK_DiemPhienChoi_xepHangCuoi", "xepHangCuoi IS NULL OR xepHangCuoi > 0");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.Entities.GameSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCaiDat");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPhienChoi");

                    b.Property<bool>("ShowCorrectAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("hienThiDapAnDung");

                    b.Property<bool>("ShowLeaderboard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("hienThiBangXepHang");

                    b.Property<bool>("ShuffleAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("xaoTronCauTraLoi");

                    b.Property<bool>("ShuffleQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("xaoTronCauHoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("GameSessionId")
                        .IsUnique();

                    b.ToTable("CaiDatPhienChoi", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.Entities.PlayerAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idTraLoi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<Guid>("GamePlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiChoi");

                    b.Property<Guid>("GameQuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoiPhien");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("laDapAnDung");

                    b.Property<int>("PointsEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diemNhan");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("int")
                        .HasColumnName("thoiGianMs");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("GamePlayerId");

                    b.HasIndex("GameQuestionId");

                    b.HasIndex("GamePlayerId", "GameQuestionId")
                        .IsUnique();

                    b.ToTable("TraLoiNguoiChoi", null, t =>
                        {
                            t.HasCheckConstraint("CK_TraLoiNguoiChoi_diemNhan", "diemNhan >= 0");

                            t.HasCheckConstraint("CK_TraLoiNguoiChoi_thoiGianMs", "thoiGianMs > 0");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPhienChoi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CurrentQuestionIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("cauHoiHienTai");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianKetThuc");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idChuPhong");

                    b.Property<string>("PIN")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("maPIN");

                    b.Property<Guid>("QuizSetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBoTracNghiem");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianBatDau");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("HostUserId");

                    b.HasIndex("QuizSetId");

                    b.HasIndex("Status");

                    b.HasIndex("PIN", "Status");

                    b.ToTable("PhienChoi", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhienChoi_cauHoiHienTai", "cauHoiHienTai >= 0");

                            t.HasCheckConstraint("CK_PhienChoi_maPIN", "LEN(maPIN) = 6 AND maPIN LIKE '[0-9][0-9][0-9][0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_PhienChoi_thoiGian", "thoiGianKetThuc IS NULL OR thoiGianKetThuc >= thoiGianBatDau");

                            t.HasCheckConstraint("CK_PhienChoi_trangThai", "trangThai IN ('Waiting', 'Started', 'Ended')");
                        });
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.QuizSetAggregate.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoi");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("noiDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("thuTu");

                    b.Property<Guid>("QuizSetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBoTracNghiem");

                    b.Property<Guid?>("QuizSetId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30)
                        .HasColumnName("giuiHanThoiGian");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loaiCauHoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.Property<int?>("VideoTimestamp")
                        .HasColumnType("int")
                        .HasColumnName("dauThoiGianVideo");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("urlVideo");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("QuizSetId");

                    b.HasIndex("QuizSetId1");

                    b.HasIndex("QuizSetId", "DisplayOrder")
                        .HasFilter("ngayXoa IS NULL");

                    b.ToTable("CauHoi", null, t =>
                        {
                            t.HasCheckConstraint("CK_CauHoi_giuiHanThoiGian", "giuiHanThoiGian > 0 AND giuiHanThoiGian <= 300");

                            t.HasCheckConstraint("CK_CauHoi_loaiCauHoi", "loaiCauHoi IN ('SingleChoice', 'TrueFalse', 'MultipleChoice', 'Matching', 'Ordering', 'Video')");

                            t.HasCheckConstraint("CK_CauHoi_thuTu", "thuTu >= 0");
                        });
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.QuizSetAggregate.Entities.QuestionStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idThongKe");

                    b.Property<int>("AverageResponseTimeMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("thoiGianTrungBinhMs");

                    b.Property<int>("CorrectAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soLanTraLoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("doDung");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoi");

                    b.Property<int>("TimesAsked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soLanHoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.Property<int>("WrongAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soLanTraLoiSai");

                    b.HasKey("Id");

                    b.HasIndex("Difficulty");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("ThongKeCauHoi", null, t =>
                        {
                            t.HasCheckConstraint("CK_ThongKeCauHoi_doDung", "doDung >= 0 AND doDung <= 100");

                            t.HasCheckConstraint("CK_ThongKeCauHoi_soLanHoi", "soLanHoi >= 0");

                            t.HasCheckConstraint("CK_ThongKeCauHoi_soLanTraLoiDung", "soLanTraLoiDung >= 0");

                            t.HasCheckConstraint("CK_ThongKeCauHoi_soLanTraLoiSai", "soLanTraLoiSai >= 0");

                            t.HasCheckConstraint("CK_ThongKeCauHoi_thoiGianTrungBinhMs", "thoiGianTrungBinhMs >= 0");
                        });
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.QuizSetAggregate.QuizSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBoTracNghiem");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("urlAnhBia");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiDung");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("moTa");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("thuTu");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("daDangTai");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieuDe");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("IsPublished");

                    b.HasIndex("IsPublished", "DeletedAt", "CreatedAt");

                    b.ToTable("BoTracNghiem", (string)null);
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idMaLamMoi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("taoLuc")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("hetHanLuc");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("thuHoiLuc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("maToken");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("capNhatLuc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("RevokedAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("MaLamMoi", (string)null);
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idVaiTro");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("moTa");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenVaiTro");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.Entities.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idMaNguoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("taoLuc")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("hetHanLuc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("maToken");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loaiToken");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("capNhatLuc");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("suDungLuc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("UsedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Type", "UsedAt");

                    b.ToTable("MaNguoiDung", null, t =>
                        {
                            t.HasCheckConstraint("CK_MaNguoiDung_loaiToken", "loaiToken IN ('PASSWORD_RESET', 'EMAIL_CONFIRMATION')");
                        });
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiDung");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("urlAnhDaiDien");

                    b.Property<string>("Bio")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gioiThieu");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenDem");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("daXacNhanEmail");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenGoi");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("matKhau");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idVaiTro");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Challenge", b =>
                {
                    b.HasOne("ThinkTogether.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThinkTogether.Domain.Aggregates.QuizSetAggregate.QuizSet", null)
                        .WithMany()
                        .HasForeignKey("QuizSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Entities.ChallengeAnswer", b =>
                {
                    b.HasOne("Domain.Aggregates.ChallengeAggregate.Entities.ChallengeAttempt", null)
                        .WithMany()
                        .HasForeignKey("ChallengeAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.ChallengeAggregate.Entities.ChallengeAttempt", null)
                        .WithMany("Answers")
                        .HasForeignKey("ChallengeAttemptId1");

                    b.HasOne("ThinkTogether.Domain.Aggregates.QuizSetAggregate.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Entities.ChallengeAttempt", b =>
                {
                    b.HasOne("Domain.Aggregates.ChallengeAggregate.Challenge", null)
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.ChallengeAggregate.Challenge", null)
                        .WithMany("Attempts")
                        .HasForeignKey("ChallengeId1");

                    b.HasOne("ThinkTogether.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domain.Aggregates.ClassAggregate.Class", b =>
                {
                    b.HasOne("ThinkTogether.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.ClassAggregate.Entities.ClassMember", b =>
                {
                    b.HasOne("Domain.Aggregates.ClassAggregate.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.ClassAggregate.Class", null)
                        .WithMany("Members")
                        .HasForeignKey("ClassId1");

                    b.HasOne("ThinkTogether.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.ClassAggregate.Entities.Homework", b =>
                {
                    b.HasOne("Domain.Aggregates.ClassAggregate.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.ClassAggregate.Class", null)
                        .WithMany("Homeworks")
                        .HasForeignKey("ClassId1");

                    b.HasOne("ThinkTogether.Domain.Aggregates.QuizSetAggregate.QuizSet", null)
                        .WithMany()
                        .HasForeignKey("QuizSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.ClassAggregate.Entities.HomeworkSubmission", b =>
                {
                    b.HasOne("Domain.Aggregates.ChallengeAggregate.Entities.ChallengeAttempt", null)
                        .WithMany()
                        .HasForeignKey("ChallengeAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.ClassAggregate.Entities.Homework", null)
                        .WithMany()
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.ClassAggregate.Entities.Homework", null)
                        .WithMany("Submissions")
                        .HasForeignKey("HomeworkId1");

                    b.HasOne("ThinkTogether.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.Entities.GamePlayer", b =>
                {
                    b.HasOne("Domain.Aggregates.GamingAggregate.GameSession", null)
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.GamingAggregate.GameSession", null)
                        .WithMany("Players")
                        .HasForeignKey("GameSessionId1");
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.Entities.GameQuestion", b =>
                {
                    b.HasOne("Domain.Aggregates.GamingAggregate.GameSession", null)
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.GamingAggregate.GameSession", null)
                        .WithMany("GameQuestions")
                        .HasForeignKey("GameSessionId1");

                    b.HasOne("ThinkTogether.Domain.Aggregates.QuizSetAggregate.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.Entities.GameScore", b =>
                {
                    b.HasOne("Domain.Aggregates.GamingAggregate.Entities.GamePlayer", null)
                        .WithMany()
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.GamingAggregate.GameSession", null)
                        .WithMany()
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.GamingAggregate.GameSession", null)
                        .WithMany("Scores")
                        .HasForeignKey("GameSessionId1");
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.Entities.GameSettings", b =>
                {
                    b.HasOne("Domain.Aggregates.GamingAggregate.GameSession", null)
                        .WithOne()
                        .HasForeignKey("Domain.Aggregates.GamingAggregate.Entities.GameSettings", "GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.Entities.PlayerAnswer", b =>
                {
                    b.HasOne("Domain.Aggregates.GamingAggregate.Entities.GamePlayer", null)
                        .WithMany()
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.GamingAggregate.Entities.GameQuestion", null)
                        .WithMany()
                        .HasForeignKey("GameQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.GameSession", b =>
                {
                    b.HasOne("ThinkTogether.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThinkTogether.Domain.Aggregates.QuizSetAggregate.QuizSet", null)
                        .WithMany()
                        .HasForeignKey("QuizSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.QuizSetAggregate.Entities.Question", b =>
                {
                    b.HasOne("ThinkTogether.Domain.Aggregates.QuizSetAggregate.QuizSet", null)
                        .WithMany()
                        .HasForeignKey("QuizSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThinkTogether.Domain.Aggregates.QuizSetAggregate.QuizSet", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuizSetId1");

                    b.OwnsMany("ThinkTogether.Domain.Aggregates.QuizSetAggregate.ValueObjects.MatchingPair", "MatchingPairs", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("idMucGhep");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("int")
                                .HasColumnName("thuTu");

                            b1.Property<string>("LeftContent")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("noiDungTrai");

                            b1.Property<string>("RightContent")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("noiDungPhai");

                            b1.Property<Guid>("idCauHoi")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("idCauHoi");

                            b1.ToTable("CauHoi_CapGhep", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("idCauHoi");
                        });

                    b.OwnsMany("ThinkTogether.Domain.Aggregates.QuizSetAggregate.ValueObjects.OrderingItem", "OrderingItems", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("idMucSapXep");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("noiDung");

                            b1.Property<int>("CorrectPosition")
                                .HasColumnType("int")
                                .HasColumnName("viTriDung");

                            b1.Property<Guid>("idCauHoi")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("idCauHoi");

                            b1.ToTable("CauHoi_SapXep", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("idCauHoi");
                        });

                    b.OwnsMany("ThinkTogether.Domain.Aggregates.QuizSetAggregate.ValueObjects.QuestionOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("idPhuongAn");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("noiDung");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("int")
                                .HasColumnName("thuTu");

                            b1.Property<string>("ImageUrl")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("urlAnh");

                            b1.Property<bool>("IsCorrect")
                                .HasColumnType("bit")
                                .HasColumnName("laDapAnDung");

                            b1.Property<Guid>("idCauHoi")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("idCauHoi");

                            b1.ToTable("CauHoi_TracNghiem", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("idCauHoi");
                        });

                    b.Navigation("MatchingPairs");

                    b.Navigation("Options");

                    b.Navigation("OrderingItems");
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.QuizSetAggregate.QuizSet", b =>
                {
                    b.HasOne("ThinkTogether.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.Entities.RefreshToken", b =>
                {
                    b.HasOne("ThinkTogether.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.Entities.UserToken", b =>
                {
                    b.HasOne("ThinkTogether.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.HasOne("ThinkTogether.Domain.Aggregates.UserAggregate.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Challenge", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Entities.ChallengeAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Domain.Aggregates.ClassAggregate.Class", b =>
                {
                    b.Navigation("Homeworks");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Domain.Aggregates.ClassAggregate.Entities.Homework", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Domain.Aggregates.GamingAggregate.GameSession", b =>
                {
                    b.Navigation("GameQuestions");

                    b.Navigation("Players");

                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.QuizSetAggregate.QuizSet", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
