// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ThinkTogether.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027072636_AddIsEmailVerifiedToUser")]
    partial class AddIsEmailVerifiedToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idThachThuc");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiTao");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<string>("Description")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<int>("PlayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("luotChoi");

                    b.Property<Guid>("QuizSetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBoTrucNghiem");

                    b.Property<bool>("ShowLeaderboard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("hienThiBangXepHang");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("trangThai");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieuDe");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("QuizSetId");

                    b.HasIndex("Status");

                    b.ToTable("ThachThuc", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Entities.ChallengeAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idLuotChoi");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idThachThuc");

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianHoanTatLuot")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CompletionTime")
                        .HasColumnType("int")
                        .HasColumnName("thoiGianHoanThanh");

                    b.Property<int>("CorrectAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soCauDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenHocSinh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("StudentName");

                    b.ToTable("LuotChoiThachThuc", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Entities.ChallengePlayerAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauTraLoi");

                    b.Property<Guid>("ChallengeSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idLuotChoiThachThuc");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("dung");

                    b.Property<int>("PointsEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diemDat");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoi");

                    b.Property<int>("SubmissionTimeSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("thoiGianNop");

                    b.Property<string>("SubmittedAnswer")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cauTraLoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeSessionId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ChallengeSessionId", "QuestionId");

                    b.ToTable("CauTraLoiThachThuc", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Entities.LeaderboardEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBangXepHang");

                    b.Property<DateTime>("AchievedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianDatDiem")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idThachThuc");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<int>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("xepHang");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenHocSinh");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ChallengeId", "Rank");

                    b.ToTable("BangXepHangThachThuc", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.GameSessionAggregate.Entities.GamePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiChoi");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trangThaiKetNoi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPhienChoi");

                    b.Property<int>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("xepHang");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("Rank");

                    b.ToTable("NguoiChoiPhien", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.GameSessionAggregate.Entities.GameQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoiPhien");

                    b.Property<double>("AverageResponseTimeSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("thoiGianTraLoiTrungBinh");

                    b.Property<int>("CorrectAnswerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soTraLoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPhienChoi");

                    b.Property<int>("IncorrectAnswerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soTraLoiSai");

                    b.Property<int>("PositionInGame")
                        .HasColumnType("int")
                        .HasColumnName("viTriTrongPhien");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("GameSessionId", "PositionInGame");

                    b.ToTable("CauHoiPhienChoi", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.GameSessionAggregate.Entities.GameScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idDiem");

                    b.Property<double>("AccuracyPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("tiLeChinhXac");

                    b.Property<int>("CorrectAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soCauDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<int>("FinalRank")
                        .HasColumnType("int")
                        .HasColumnName("xepHangCuoi");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPhienChoi");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiChoi");

                    b.Property<int>("TotalQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("tongSoCau");

                    b.Property<int>("TotalScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("tongDiem");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("TotalScore")
                        .IsDescending();

                    b.HasIndex("GameSessionId", "FinalRank");

                    b.ToTable("DiemPhienChoi", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.GameSessionAggregate.Entities.GameSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCaiDat");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPhienChoi");

                    b.Property<bool>("ShowCorrectAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("hienThiDapAnDung");

                    b.Property<bool>("ShowLeaderboard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("hienThiBangXepHang");

                    b.Property<bool>("ShuffleAnswers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("xaoTronCauTraLoi");

                    b.Property<bool>("ShuffleQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("xaoTronCauHoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("GameSessionId")
                        .IsUnique();

                    b.ToTable("CaiDatPhienChoi", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.GameSessionAggregate.Entities.PlayerAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauTraLoi");

                    b.Property<string>("Answer")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDungTraLoi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<Guid>("GamePlayerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiChoi");

                    b.Property<Guid?>("GameSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("dung");

                    b.Property<int>("PointsEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("diemDat");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoi");

                    b.Property<int>("TimeToAnswer")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("GamePlayerId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("CauTraLoiNguoiChoi", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.GameSessionAggregate.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPhienChoi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CurrentQuestionIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("cauHoiHienTai");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianKetThuc");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idChuPhong");

                    b.Property<Guid>("QuizSetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBoTrucNghiem");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianBatDau");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("trangThai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("HostId");

                    b.HasIndex("QuizSetId");

                    b.HasIndex("Status");

                    b.ToTable("PhienChoi", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.QuizSetAggregate.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoi");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noiDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("thuTu");

                    b.Property<Guid>("QuizSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimeLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30)
                        .HasColumnName("giuiHanThoiGian");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("loaiCauHoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Order");

                    b.HasIndex("QuizSetId");

                    b.ToTable("CauHoi", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.QuizSetAggregate.Entities.QuestionStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idThongKe");

                    b.Property<double>("AverageResponseTimeSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("thoiGianTraLoiTrungBinh");

                    b.Property<int>("CorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soTraLoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<double>("DifficultyPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0)
                        .HasColumnName("tiLeKho");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idPhienChoi");

                    b.Property<int>("IncorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("soTraLoiSai");

                    b.Property<string>("MostSelectedAnswer")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cauTraLoiDuocChonNhieu");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idCauHoi");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("GameSessionId", "QuestionId")
                        .IsUnique();

                    b.ToTable("ThongKeCauHoi", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.QuizSetAggregate.QuizSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBoTrucNghiem");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("urlAnhBia");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<string>("Description")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moTa");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("thuTu");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("daDangTai");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tieuDe");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("IsPublished");

                    b.HasIndex("UserId");

                    b.ToTable("BoTrucNghiem", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.UserAggregate.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idMaLamMoi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("taoLuc")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("hetHanLuc");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("thuHoiLuc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("maToken");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("capNhatLuc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("RevokedAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("MaLamMoi", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.UserAggregate.Entities.UserToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idMaNguoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("taoLuc")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("hetHanLuc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("maToken");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loaiToken");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("capNhatLuc");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("suDungLuc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("UsedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Type", "UsedAt");

                    b.ToTable("MaNguoiDung", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiDung");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("urlAnhDaiDien");

                    b.Property<string>("Bio")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gioiThieu");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenDem");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("daXacNhanEmail");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenGoi");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("matKhau");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("vaiTro");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNhatKy");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("hanhDong");

                    b.Property<Guid>("ChangedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiThayDoi");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("thoiGianThayDoi")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idThucThe");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("loaiThucThe");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("diaChiIP");

                    b.Property<string>("NewValues")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("giaTriMoi");

                    b.Property<string>("OldValues")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("giaTriCu");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ChangedById");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idMedia");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTaiLen")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayXoa");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("thoiLuongGiay");

                    b.Property<int>("FileSizeBytes")
                        .HasColumnType("int")
                        .HasColumnName("kichThuocByte");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("tenFile");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("loaiMime");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("loai");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNguoiTaiLen");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Type");

                    b.HasIndex("UploadedById");

                    b.ToTable("Media", (string)null);
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.Entities.ModeratorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idNhatKy");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("hanhDong");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idQuanTri");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idThucThe");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("loaiThucThe");

                    b.Property<string>("Notes")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghiChu");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lyDo");

                    b.Property<bool>("Resolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("daGiaiQuyet");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayGiaiQuyet");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("AdminId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityType");

                    b.HasIndex("Resolved");

                    b.HasIndex("ResolvedAt");

                    b.ToTable("NhatKyQuanTri", (string)null);
                });

            modelBuilder.Entity("ThinkTogether.Domain.Aggregates.UserAggregate.Entities.ProfanityFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idBoLoc");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("dangHoatDong");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pattern");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("mucDoNghiemTrong");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCapNhat");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Pattern")
                        .IsUnique();

                    b.HasIndex("Severity");

                    b.ToTable("BoLocTuMieng", (string)null);
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Challenge", b =>
                {
                    b.OwnsOne("Domain.Aggregates.ChallengeAggregate.ValueObjects.ShareableLink", "ShareLink", b1 =>
                        {
                            b1.Property<Guid>("ChallengeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("urlChiaSeLink");

                            b1.HasKey("ChallengeId");

                            b1.ToTable("ThachThuc");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeId");
                        });

                    b.Navigation("ShareLink")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Entities.ChallengeAttempt", b =>
                {
                    b.HasOne("Domain.Aggregates.ChallengeAggregate.Challenge", null)
                        .WithMany("Attempts")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Aggregates.ChallengeAggregate.ValueObjects.ChallengeScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("ChallengeAttemptId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("diemDat");

                            b1.HasKey("ChallengeAttemptId");

                            b1.ToTable("LuotChoiThachThuc");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeAttemptId");
                        });

                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Entities.LeaderboardEntry", b =>
                {
                    b.HasOne("Domain.Aggregates.ChallengeAggregate.Challenge", null)
                        .WithMany("Leaderboard")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Aggregates.ChallengeAggregate.ValueObjects.ChallengeScore", "Score", b1 =>
                        {
                            b1.Property<Guid>("LeaderboardEntryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("diemCaoNhat");

                            b1.HasKey("LeaderboardEntryId");

                            b1.ToTable("BangXepHangThachThuc");

                            b1.WithOwner()
                                .HasForeignKey("LeaderboardEntryId");
                        });

                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.GameSessionAggregate.Entities.GamePlayer", b =>
                {
                    b.HasOne("Domain.Aggregates.GameSessionAggregate.GameSession", null)
                        .WithMany("Players")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Aggregates.GameSessionAggregate.ValueObjects.PlayerNickname", "Nickname", b1 =>
                        {
                            b1.Property<Guid>("GamePlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("thamDuOi");

                            b1.HasKey("GamePlayerId");

                            b1.ToTable("NguoiChoiPhien");

                            b1.WithOwner()
                                .HasForeignKey("GamePlayerId");
                        });

                    b.OwnsOne("Domain.Aggregates.GameSessionAggregate.ValueObjects.Score", "Score", b1 =>
                        {
                            b1.Property<Guid>("GamePlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(0)
                                .HasColumnName("diem");

                            b1.HasKey("GamePlayerId");

                            b1.ToTable("NguoiChoiPhien");

                            b1.WithOwner()
                                .HasForeignKey("GamePlayerId");
                        });

                    b.Navigation("Nickname")
                        .IsRequired();

                    b.Navigation("Score")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.GameSessionAggregate.Entities.GameSettings", b =>
                {
                    b.HasOne("Domain.Aggregates.GameSessionAggregate.GameSession", null)
                        .WithOne("Settings")
                        .HasForeignKey("Domain.Aggregates.GameSessionAggregate.Entities.GameSettings", "GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.GameSessionAggregate.Entities.PlayerAnswer", b =>
                {
                    b.HasOne("Domain.Aggregates.GameSessionAggregate.GameSession", null)
                        .WithMany("Answers")
                        .HasForeignKey("GameSessionId");
                });

            modelBuilder.Entity("Domain.Aggregates.GameSessionAggregate.GameSession", b =>
                {
                    b.OwnsOne("Domain.Aggregates.GameSessionAggregate.ValueObjects.GamePin", "PIN", b1 =>
                        {
                            b1.Property<Guid>("GameSessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("nvarchar(6)")
                                .HasColumnName("maPIN");

                            b1.HasKey("GameSessionId");

                            b1.ToTable("PhienChoi");

                            b1.WithOwner()
                                .HasForeignKey("GameSessionId");
                        });

                    b.Navigation("PIN")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.QuizSetAggregate.Entities.Question", b =>
                {
                    b.HasOne("Domain.Aggregates.QuizSetAggregate.QuizSet", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuizSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.Aggregates.QuizSetAggregate.ValueObjects.Answer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("idCauHoi")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(-1)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("noiDung");

                            b1.Property<string>("ImageUrl")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("urlAnh");

                            b1.Property<bool>("IsCorrect")
                                .HasColumnType("bit")
                                .HasColumnName("laDapAnDung");

                            b1.Property<int>("Order")
                                .HasColumnType("int")
                                .HasColumnName("thuTu");

                            b1.HasKey("idCauHoi", "Id");

                            b1.ToTable("CauTraLoi", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("idCauHoi");
                        });

                    b.OwnsMany("Domain.Aggregates.QuizSetAggregate.ValueObjects.MatchPair", "MatchPairs", b1 =>
                        {
                            b1.Property<Guid>("idCauHoi")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("LeftContent")
                                .IsRequired()
                                .HasMaxLength(-1)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("noiDungTrai");

                            b1.Property<int>("Order")
                                .HasColumnType("int")
                                .HasColumnName("thuTu");

                            b1.Property<string>("RightContent")
                                .IsRequired()
                                .HasMaxLength(-1)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("noiDungPhai");

                            b1.HasKey("idCauHoi", "Id");

                            b1.ToTable("CapGhep", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("idCauHoi");
                        });

                    b.OwnsMany("Domain.Aggregates.QuizSetAggregate.ValueObjects.OrderItem", "OrderItems", b1 =>
                        {
                            b1.Property<Guid>("idCauHoi")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasMaxLength(-1)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("noiDung");

                            b1.Property<int>("CorrectPosition")
                                .HasColumnType("int")
                                .HasColumnName("viTriDung");

                            b1.HasKey("idCauHoi", "Id");

                            b1.ToTable("MucSapXep", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("idCauHoi");
                        });

                    b.Navigation("Answers");

                    b.Navigation("MatchPairs");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domain.Aggregates.UserAggregate.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Aggregates.UserAggregate.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.UserAggregate.Entities.UserToken", b =>
                {
                    b.HasOne("Domain.Aggregates.UserAggregate.User", null)
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Aggregates.ChallengeAggregate.Challenge", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Leaderboard");
                });

            modelBuilder.Entity("Domain.Aggregates.GameSessionAggregate.GameSession", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Players");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Domain.Aggregates.QuizSetAggregate.QuizSet", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
